[package]
name = "wood"
description = "A robust material that is simple to work: Parsing, serialization and deserialization for termpose and nakedlist"
version = "0.2.1"
authors = ["mako <marcus.yass@gmail.com>"]
licence = "MIT"


[dependencies]
#string_cache = "0.7.0"
ref_slice = "1.1.1"