[package]
name = "termpose"
description = "Deserialization for termpose and s-expressions"
version = "0.2.0"
authors = ["mako <marcus.yass@gmail.com>"]

[dependencies]
#string_cache = "0.7.0"
ref_slice = "1.1.1"